### PR TITLE
Add changelog notes for migrating to Orka 3.*

### PR DESCRIPTION
**Pull request by kkyriakidis**

### CODE REVIEW

**Review by nikostoulas — APPROVED** [review]
Thank you @kkyriakidis . Are any steps necessary to migrate an app to latest orka that we could also mention? E.g. maybe a mongodb version compatibility check?

**Review by klesgidis — APPROVED** [review]

**Comment by kkyriakidis** [comment]
The mongoDB Node.js driver derives from the mongoose version. Unless specific stated. There can be incompatibilities with libraries using the driver. In our case in assessments we had an issue with ts-mongoose for example. 

Also we had breaking changes noted to the mongoose migration guide 
Types.ObjectId is now a class, which means you can no longer omit new when creating a new ObjectId using new mongoose.Types.ObjectId(). Currently, you can still omit new in JavaScript, but you must put new in TypeScript.
Do you think I should specific add this to the orka changelog? @nikostoulas

**Comment by nikostoulas** [comment]
> The mongoDB Node.js driver derives from the mongoose version. Unless specific stated. There can be incompatibilities with libraries using the driver. In our case in assessments we had an issue with ts-mongoose for example.
> 
> Also we had breaking changes noted to the mongoose migration guide Types.ObjectId is now a class, which means you can no longer omit new when creating a new ObjectId using new mongoose.Types.ObjectId(). Currently, you can still omit new in JavaScript, but you must put new in TypeScript. Do you think I should specific add this to the orka changelog? @nikostoulas

If you think they are common sure. If not then link to the docs is ok.

**Review by nikostoulas — APPROVED** [review]
⭐

**Pull request merged**
