### PR TITLE
[PROD-1677][ENG-75] Automatically pass trace information on request headers

### PR DESCRIPTION
**Pull request by klesgidis**
## Summary
* Always initialize riviere on orka builder
* Add new HTTP proxy that automatically appends trace id to all requests, if exists

### CODE REVIEW

**Review by nikostoulas — APPROVED** [review]
💯

**Comment by nikostoulas** [comment]
I was wondering if we should rename the default traceHeaderName(maybe x-orka-id) as istio overwrites x-request-id. WDYT?

**Comment by klesgidis** [comment]
> I was wondering if we should rename the default traceHeaderName(maybe x-orka-id) as istio overwrites x-request-id. WDYT?

this will affect all apps, and won't be backwards compatible. I don't have a problem renaming it, but maybe we should contact code owners?

**Comment by nikostoulas** [comment]
> > I was wondering if we should rename the default traceHeaderName(maybe x-orka-id) as istio overwrites x-request-id. WDYT?
> 
> this will affect all apps, and won't be backwards compatible. I don't have a problem renaming it, but maybe we should contact code owners?

We haven't released v2 yet so that's ok. In any case this changes through env configuration. This hasn't to do with this pr, so feel free to merge this.

**Review by nikosd23 — COMMENTED** [review]
🥇

**Pull request merged**
